### ISSUE TITLE
auth via gmail?

### ISSUE THREAD

**Issue by hopewise** [robinboening/alchemy-oauth#1]
Hello,

Is there an example to use gmail account to authenticate users into app?

Thank you!

**Comment by tvdeyen** [comment]
This gem provides an oauth endpoint for apps that want to authenticate against an Alchemy user. It does not provide oauth login for Alchemy. 

And please be aware that this here is an issue tracker. Not a Q&A forum. 

Please ask such questions in Stackoverflow, the Google Usergroup or the Gitter channel. 

Thanks
